services:
  backend:
    build: .
    depends_on:
      - redis
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: testAdmin
      POSTGRES_PASSWORD: testPass
      POSTGRES_DB: elrif
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env


volumes:
  postgres_data: